import "./globals.css";
import "./burger.css";
import { Navbar } from "./components/Navbar/Navbar";
import { Footer } from "./components/Footer/Footer";
import Image from "next/image";
import logo from "../../public/navbar/logo.png";

export const metadata = {
  title: "Dr. Moanack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className="scrollbar-thin scrollbar-track-moanackDarkGrey scrollbar-thumb-moanackGrey scroll-smooth min-h-screen antialiased"
      suppressHydrationWarning
    >
      <body>
        <Navbar />
        {children}
        <Footer />
        {/* <Image src={logo} alt="logo" />
        <h1>SITIO EN CONSTRUCCIÓN</h1> */}
      </body>
    </html>
  );
}
