import "./globals.css";
import { Navbar } from "./components/Navbar/Navbar";
import { Footer } from "./components/Footer/Footer";
import Image from "next/image";
import logo from "../../public/navbar/logo.png";

export const metadata = {
  title: "Moanack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        {children}
        <Footer />
        {/* <Image src={logo} alt="logo" />
        <h1>SITIO EN CONSTRUCCIÓN</h1> */}
      </body>
    </html>
  );
}
